/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.ine5612.apresentacao;

import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author aluno
 */
public class AdicionaProdutoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComandaJFrame
     */
    
    private Container container;
    
    private JLabel labelTitulo;
    private JLabel labelPedido;
    private JLabel valor;
    
    
    
    public AdicionaProdutoJFrame() {
        initComponents();
        
        container =  getContentPane();
        inicializarComponentes();
        setSize(400,220);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    
    private void inicializarComponentes(){
    
        container.setLayout(new GridBagLayout());
        
        GridBagConstraints cts = new GridBagConstraints();
        
        for (int i = 0; i < 5; i++) {
            
        labelPedido = new JLabel("Pedido X................");
        cts.gridx = 0;
	cts.gridy = i;
	cts.fill = GridBagConstraints.BOTH;
	container.add(labelPedido, cts);
        }
        
        for (int i = 0; i < 5; i++) {
            
        valor = new JLabel("Valor Pedido X");
        cts.gridx = 1;
	cts.gridy = i;
	cts.fill = GridBagConstraints.BOTH;
	container.add(valor, cts);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
