/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.ine5612.apresentacao;

import br.ufsc.ine5612.controle.ControladorFuncionario;
import java.awt.Container;
import java.awt.Dimension;
import br.ufsc.ine5612.controle.ControladorPrincipal;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author aluno
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    private Container container;

    private JLabel labelTitulo;
    private JLabel labelLogin;
    private JLabel labelSenha;

    private JTextField textFieldLogin;
    private JPasswordField textFieldSenha;

    private JButton btAcesso;
    private JButton btCadastra;
    
    private ControladorFuncionario funcionario;
    private GerenciadorEventos gerenciadorEventos;

    public LoginJFrame(ControladorFuncionario funcionario) {
        initComponents();
        
        this.funcionario = funcionario;
        
        container = getContentPane();
        this.gerenciadorEventos = new GerenciadorEventos();

        inicializarComponentes();

        setSize(400, 220);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

    }

    private void inicializarComponentes() {

        container.setLayout(new GridBagLayout());

        GridBagConstraints cts = new GridBagConstraints();

        labelTitulo = new JLabel("Darayama - Gerenciamento de Pedidos");
//        cts.gridx = 0;
//	cts.gridy = 0;
        cts.anchor = GridBagConstraints.PAGE_START;
        cts.fill = GridBagConstraints.BOTH;
        container.add(labelTitulo, cts);

        labelLogin = new JLabel("Login:");
        cts.gridx = 0;
        cts.gridy = 1;
        cts.fill = GridBagConstraints.BOTH;
        container.add(labelLogin, cts);

        labelSenha = new JLabel("Senha:");
        cts.gridx = 0;
        cts.gridy = 2;
        cts.fill = GridBagConstraints.BOTH;
        container.add(labelSenha, cts);

        textFieldLogin = new JTextField();
        textFieldLogin.setPreferredSize(new Dimension(150, 20));
        cts.gridx = 1;
        cts.gridy = 1;
        cts.fill = GridBagConstraints.BOTH;
        container.add(textFieldLogin, cts);

        textFieldSenha = new JPasswordField();
        textFieldSenha.setPreferredSize(new Dimension(150, 20));
        cts.gridx = 1;
        cts.gridy = 2;
        cts.fill = GridBagConstraints.BOTH;
        container.add(textFieldSenha, cts);

        btAcesso = new JButton("Login");
        btAcesso.setActionCommand(btAcesso.getText());
        cts.gridx = 1;
        cts.gridy = 3;
        cts.insets = new Insets(15, 5, 5, 15);
        cts.fill = GridBagConstraints.BOTH;
        container.add(btAcesso, cts);
        btAcesso.addActionListener(gerenciadorEventos);

    }
    
    private class GerenciadorEventos implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            if (e.getActionCommand().equals(btAcesso.getActionCommand())) {
               funcionario.validaUsuario(textFieldLogin.getText(),textFieldSenha.getText());
//             principal.telaMesasSelecao();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
